    var page10SS = new slideshow('page10_SS', 'page10',{
        withPagination  :   true,
        withArrows      :   true,
        slideDirection  :   'LTR',
        withPhotoswipe  :   false,
        isLooped        :   false,
        isAutoplayed    :   false,
        autoplaySpeed   :   2500,
        componentData   :   [
            {
                type: "gallery", 
                galleryId:'page10Gallery_1', 
                galleryTitle:'Testing an Electromagnet',
                titleAsCaption:true,
                galleryThumb:'images/page10/RUS_L2_M6_mov_1_sml.jpg', 
                galleryImage:'images/page10/RUS_L2_M6_mov_1.jpg',
                galleryText:'Use the circuit diagram, the list of materials, and the steps in this slide show to test your electromagnet.To complete each step:read the step, then watch the video to see it being done.Then do the step yourself.', 
                textPosition: 'bottom',
                textRatio: 'oneThird', 
                withAudio: false,
            },
            {
                type: "gallery", 
                galleryId:'page10Gallery_2', 
                galleryCaption:'',
                galleryThumb:'images/page10/RUS_L2_M6_003_PHO_001_sml.jpg', 
                galleryImage:'images/page10/RUS_L2_M6_003_PHO_001.jpg',
                galleryText:'<img src="images/audio-icon.png" class="audioIcon audio-icon" audiosource="sounds/page10/RUS_L2_M6_SB_010_A001.mp3" alt=""/><span class="audioText">Examine the electromagnet’s circuit diagram carefully. Then click forward to watch how to test your electromagnet. If you want to look at this circuit diagram at any time, just return to this slide to view it again.</span>', 
                textPosition: 'bottom',
                textRatio: 'oneThird', 
                withAudio: false,
            },
            {
                type: "gallery", 
                galleryId:'page10Gallery_3', 
                galleryCaption:'Step 1: Apparatus',
                galleryThumb:'images/page10/RUS_L2_M6_mov_2_sml.jpg', 
                galleryVideo:'videos/page10/RUS_L2_M6_mov_2.mov',
                galleryText:'<img src="images/audio-icon.png" class="audioIcon audio-icon" audiosource="sounds/page10/RUS_L2_M6_SB_010_A002.mp3" alt=""/><span class="audioText">Step 1: Check that you have all apparatus. You need an iron bolt, a 3-meter length of wire, a D-cell battery, some sticky tape, a scissors and some paper clips.</span>', 
                textPosition: 'bottom',
                textRatio: 'oneThird', 
                withAudio: false,
            },
            {
                type: "gallery", 
                galleryId:'page10Gallery_4', 
                galleryCaption:'Step 2: Table',
                galleryThumb:'images/page10/RUS_L2_M6_mov_3_sml.jpg', 
                galleryVideo:'videos/page10/RUS_L2_M6_mov_3.mov',
                galleryText:'<img src="images/audio-icon.png" class="audioIcon audio-icon" audiosource="sounds/page10/RUS_L2_M6_SB_010_A003.mp3" alt=""/><span class="audioText">Step 2: Create a Results table like this for recording all results. You will perform five trials.</span>', 
                textPosition: 'bottom',
                textRatio: 'oneThird', 
                withAudio: false,
            },
            {
                type: "gallery", 
                galleryId:'page10Gallery_5', 
                galleryCaption:'Trial 1: 40 Coils',
                galleryThumb:'images/page10/RUS_L2_M6_mov_4_sml.jpg', 
                galleryVideo:'videos/page10/RUS_L2_M6_mov_4.mov',
                galleryTitle:'Trial 1: Coiling the wire',
                galleryText:'<img src="images/audio-icon.png" class="audioIcon audio-icon" audiosource="sounds/page10/RUS_L2_M6_SB_010_A004.mp3" alt=""/><span class="audioText">Step 3: Perform Trial 1. Coil the wire tightly around the middle of the bolt until you have 40 coil turns. Use the middle portion of the wire, leaving plenty of loose wire on either side on either side. Make sure that the coils fit snugly together, and make sure to count the number of coil turns.</span>', 
                textPosition: 'bottom',
                textRatio: 'oneThird', 
                withAudio: false,
            },
            {
                type: "gallery", 
                galleryId:'page10Gallery_6', 
                galleryCaption:'Trial 1: Fastening',
                galleryTitle:'Trial 1: Securing the wire',
                galleryThumb:'images/page10/RUS_L2_M6_mov_5_sml.jpg', 
                galleryVideo:'videos/page10/RUS_L2_M6_mov_5.mov',
                galleryText:'<img src="images/audio-icon.png" class="audioIcon audio-icon" audiosource="sounds/page10/RUS_L2_M6_SB_010_A005.mp3" alt=""/><span class="audioText">Step 4: Use tape to fasten the coil at the top and bottom of the bolt so that the coil doesn’t unravel.</span>', 
                textPosition: 'bottom',
                textRatio: 'oneThird', 
                withAudio: false,
            },
            {
                type: "gallery", 
                galleryId:'page10Gallery_7', 
                galleryCaption:'Trial 1: Recording',
                galleryTitle:'Trial 1: Recording the number of coil turns',
                galleryThumb:'images/page10/RUS_L2_M6_mov_6_sml.jpg', 
                galleryVideo:'videos/page10/RUS_L2_M6_mov_6.mov',
                galleryText:'<img src="images/audio-icon.png" class="audioIcon audio-icon" audiosource="sounds/page10/RUS_L2_M6_SB_010_A006.mp3" alt=""/><span class="audioText">Step 5: Note the number of coil turns in your table for this trial, which is trial 1.</span>', 
                textPosition: 'bottom',
                textRatio: 'oneThird', 
                withAudio: false,
            },
            {
                type: "gallery", 
                galleryId:'page10Gallery_8', 
                galleryCaption:'Trial 1: Connecting',
                galleryThumb:'images/page10/RUS_L2_M6_mov_7_sml.jpg', 
                galleryVideo:'videos/page10/RUS_L2_M6_mov_7.mov',
                galleryTitle:'Trial 1: Connecting the wire to the battery',
                galleryText:'<img src="images/audio-icon.png" class="audioIcon audio-icon" audiosource="sounds/page10/RUS_L2_M6_SB_010_A007.mp3" alt=""/><span class="audioText">Step 6: Tape either bare end of wire to the positive and negative terminals of the battery. Make sure the wire is in contact with each battery terminal. Be careful, as sometimes the terminals can get warm!</span>', 
                textPosition: 'bottom',
                textRatio: 'oneThird', 
                withAudio: false,
            },
            {
                type: "gallery", 
                galleryId:'page10Gallery_9', 
                galleryCaption:'Trial 1: Testing',
                galleryThumb:'images/page10/RUS_L2_M6_mov_8_sml.jpg', 
                galleryVideo:'videos/page10/RUS_L2_M6_mov_8.mov',
                galleryTitle:'Trial 1: Testing the strength of the electromagnet',
                galleryText:'<img src="images/audio-icon.png" class="audioIcon audio-icon" audiosource="sounds/page10/RUS_L2_M6_SB_010_A008.mp3" alt=""/><span class="audioText">Step 7: Place the tip of the electromagnet in the pile of paper clips and lift it up, picking up as many paper clips as it can lift.</span>', 
                textPosition: 'bottom',
                textRatio: 'oneThird', 
                withAudio: false,
            },
            {
                type: "gallery", 
                galleryId:'page10Gallery_10', 
                galleryCaption:'Trial 1: Recording',
                galleryThumb:'images/page10/RUS_L2_M6_mov_9_sml.jpg', 
                galleryVideo:'videos/page10/RUS_L2_M6_mov_9.mov',
                galleryTitle:'Trial 1: Recording the number of paper clips picked up',
                galleryText:'<img src="images/audio-icon.png" class="audioIcon audio-icon" audiosource="sounds/page10/RUS_L2_M6_SB_010_A009.mp3" alt=""/><span class="audioText">Step 8: In your table, note the number of paper clips picked up for this trial, which is trial 1.</span>', 
                textPosition: 'bottom',
                textRatio: 'oneThird', 
                withAudio: false,
            },
            {
                type: "gallery", 
                galleryId:'page10Gallery_11', 
                galleryCaption:'Trial 1: Disconnecting',
                galleryThumb:'images/page10/RUS_L2_M6_mov_10_sml.jpg', 
                galleryVideo:'videos/page10/RUS_L2_M6_mov_10.mov',
                galleryTitle:'Trial 1: Disconnecting the battery',
                galleryText:'<img src="images/audio-icon.png" class="audioIcon audio-icon" audiosource="sounds/page10/RUS_L2_M6_SB_010_A010.mp3" alt=""/><span class="audioText">Step 9: To save your battery, disconnect the circuit by removing at least one wire from either battery terminal.</span>', 
                textPosition: 'bottom',
                textRatio: 'oneThird', 
                withAudio: false,
            },
            {
                type: "gallery", 
                galleryId:'page10Gallery_12', 
                galleryCaption:'Trial 2: 60 Coils',
                galleryThumb:'images/page10/RUS_L2_M6_mov_11_sml.jpg', 
                galleryVideo:'videos/page10/RUS_L2_M6_mov_11.mov',
                galleryTitle:'Trial 2',
                galleryText:'<img src="images/audio-icon.png" class="audioIcon audio-icon" audiosource="sounds/page10/RUS_L2_M6_SB_010_A011.mp3" alt=""/><span class="audioText">Step 10: Perform Trial 2. Coil the wire tightly around the middle of the nail until there are 60 coil turns. Tape the ends as shown, and reconnect the battery. Pick up paper clips with the electromagnet. Count the number of paper clips picked up in and note the number in your table. Make sure to disconnect your battery when you’ve finished the trial.</span>', 
                textPosition: 'bottom',
                textRatio: 'oneThird', 
                withAudio: false,
            },
            {
                type: "gallery", 
                galleryId:'page10Gallery_13',
                galleryCaption:'Trial 3: 80 Coils',
                galleryThumb:'images/page10/RUS_L2_M6_mov_12_sml.jpg', 
                galleryVideo:'videos/page10/RUS_L2_M6_mov_12.mov',
                galleryText:'<img src="images/audio-icon.png" class="audioIcon audio-icon" audiosource="sounds/page10/RUS_L2_M6_SB_010_A012.mp3" alt=""/><span class="audioText">Step 11: Perform Trial 3. Coil the wire tightly around the middle of the nail until there are eighty coil turns. Tape the ends as shown, and reconnect the battery. Pick up paper clips with the electromagnet. Count the number of paper clips picked up in and note the number in your table. Make sure to disconnect your battery when you’ve finished the trial.</span>', 
                textPosition: 'bottom',
                textRatio: 'oneThird', 
                withAudio: false,
            },
            {
                type: "gallery", 
                galleryId:'page10Gallery_14', 
                galleryCaption:'Trial 4: 100 Coils',
                galleryThumb:'images/page10/RUS_L2_M6_mov_13_sml.jpg', 
                galleryVideo:'videos/page10/RUS_L2_M6_mov_13.mov',
                galleryTitle:'Trial 4', 
                galleryText:'<img src="images/audio-icon.png" class="audioIcon audio-icon" audiosource="sounds/page10/RUS_L2_M6_SB_010_A013.mp3" alt=""/><span class="audioText">Step 12: Perform Trial 4. Coil the wire tightly around the middle of the nail until there are 100 coil turns. Tape the ends as shown, and reconnect the battery. Pick up paper clips with the electromagnet. Count the number of paper clips picked up in and note the number in your table. Make sure to disconnect your battery when you’ve finished the trial.</span>', 
                textPosition: 'bottom',
                textRatio: 'oneThird', 
                withAudio: false,
            },
            {
                type: "gallery", 
                galleryId:'page10Gallery_15', 
                galleryCaption:'Trial 5: 120 Coils',
                galleryThumb:'images/page10/RUS_L2_M6_mov_14_sml.jpg', 
                galleryVideo:'videos/page10/RUS_L2_M6_mov_14.mov',
                galleryTitle:'Trial 5', 
                galleryText:'<img src="images/audio-icon.png" class="audioIcon audio-icon" audiosource="sounds/page10/RUS_L2_M6_SB_010_A014.mp3" alt=""/><span class="audioText">Step 13: Perform Trial 5. Coil the wire tightly around the middle of the nail until there are 120 coil turns. Tape the ends as shown, and reconnect the battery. Pick up paper clips with the electromagnet. Count the number of paper clips picked up in and note the number in your table. Make sure to disconnect your battery when you’ve finished the trial.</span>', 
                textPosition: 'bottom',
                textRatio: 'oneThird', 
                withAudio: false,
            },
            {
                type: "gallery", 
                galleryId:'page10Gallery_16', 
                galleryCaption:'Disconnect',
                galleryThumb:'images/page10/RUS_L2_M6_mov_15_sml.jpg', 
                galleryVideo:'videos/page10/RUS_L2_M6_mov_15.mov',
                galleryText:'<img src="images/audio-icon.png" class="audioIcon audio-icon" audiosource="sounds/page10/RUS_L2_M6_SB_010_A015.mp3" alt=""/><span class="audioText">Step 14: Finally, disconnect the battery.</span>', 
                textPosition: 'bottom',
                textRatio: 'oneThird', 
                withAudio: false,
            }
        ],
        isThumbnail         :   false,
        withRubric          :   false,
        fullScreenHeight    :   '93%',
        template            :   templateType.RiseBlue,
        componentPageName   :   'page10'
    });
    