    var page3SS = new slideshow('page3_SS', 'page3',{
        withPagination  :   true,
        withArrows      :   true,
        slideDirection  :   'LTR',
        withPhotoswipe  :   false,
        isLooped        :   false,
        isAutoplayed    :   false,
        autoplaySpeed   :   2500,
        componentData   :   [
            {
                type: "gallery", 
                galleryId:'page3Gallery_1',
                galleryTitle: 'Building an Electromagnet',
                galleryThumb:'images/page3/RUS_L2_M6_mov_1_sml.jpg', 
                titleAsCaption  :   true,
                galleryImage:'images/page3/RUS_L2_M6_mov_1.jpg', 
                galleryText:'Use the circuit diagram, the list of materials, and the steps in this slide show to build your own electromagnet.To complete each procedure step, read the step, then watch the video to see it being done.Then do the step yourself.', 
                textPosition: 'bottom',
                textRatio: 'oneThird', 
                withAudio: false,
            },
            {
                type: "gallery", 
                galleryId:'page3Gallery_2',  
                galleryThumb:'images/page3/RUS_L2_M6_003_PHO_001.jpg', 
                galleryImage:'images/page3/RUS_L2_M6_003_PHO_001.jpg', 
                galleryText:'<img src="images/audio-icon.png" class="audioIcon audio-icon" audiosource="sounds/page3/RUS_L2_M6_SB_003_A001.mp3" alt=""/><span class="audioText">Examine the electromagnet’s circuit diagram carefully. Then click forward to watch a video and start making your own electromagnet. If you want to return to look at this circuit diagram at any time, just return to this slide to view it again.</span>', 
                textPosition: 'bottom',
                textRatio: 'oneThird',
                withAudio: false,
            },
            {
                type: "gallery", 
                galleryId:'page3Gallery_3',  
                galleryCaption:'Step 1: Apparatus',
                galleryThumb:'images/page3/RUS_L2_M6_mov_2_sml.jpg', 
                galleryVideo:'videos/page3/RUS_L2_M6_mov_2.mov', 
                galleryText:'<img src="images/audio-icon.png" class="audioIcon audio-icon" audiosource="sounds/page3/RUS_L2_M6_SB_003_A002.mp3" alt=""/><span class="audioText">Step 1: Check that you have all apparatus. You need an iron bolt, a 3-meter length of wire, a D-cell battery, some electrical tape, a scissors and some paper clips.</span>', 
                textPosition: 'bottom',
                textRatio: 'oneThird', 
                withAudio: false,
            },
            {
                type: "gallery", 
                galleryId:'page3Gallery_4',  
                galleryCaption:'Step 2: Coiling',
                galleryThumb:'images/page3/RUS_L2_M6_mov_4_sml.jpg', 
                galleryVideo:'videos/page3/RUS_L2_M6_mov_4.mov', 
                galleryText:'<img src="images/audio-icon.png" class="audioIcon audio-icon" audiosource="sounds/page3/RUS_L2_M6_SB_003_A003.mp3" alt=""/><span class="audioText">Step 2: Coil the wire tightly around the middle of the bolt until you have 40 coil turns. Use the middle portion of the wire, leaving plenty of loose wire on either side. Make sure that the coils fit snugly together, and make sure to count the number of coil turns.</span>', 
                textPosition: 'bottom',
                textRatio: 'oneThird', 
                withAudio: false,
            },
            {
                type: "gallery", 
                galleryId:'page3Gallery_5',  
                galleryCaption:'Step 3: Fastening',
                galleryThumb:'images/page3/RUS_L2_M6_mov_5_sml.jpg', 
                galleryVideo:'videos/page3/RUS_L2_M6_mov_5.mov', 
                galleryText:'<img src="images/audio-icon.png" class="audioIcon audio-icon" audiosource="sounds/page3/RUS_L2_M6_SB_003_A004.mp3" alt=""/><span class="audioText">Step 3: Use tape to fasten your coil at either end of the bolt so that the coil doesn’t unravel.</span>', 
                textPosition: 'bottom',
                textRatio: 'oneThird', 
                withAudio: false,
            },
            {
                type: "gallery", 
                galleryId:'page3Gallery_6',  
                galleryCaption:'Step 4: Connecting',
                galleryThumb:'images/page3/RUS_L2_M6_mov_7_sml.jpg', 
                galleryVideo:'videos/page3/RUS_L2_M6_mov_7.mov', 
                galleryText:'<img src="images/audio-icon.png" class="audioIcon audio-icon" audiosource="sounds/page3/RUS_L2_M6_SB_003_A005.mp3" alt=""/><span class="audioText">Step 4: Tape the bare ends of wire to the positive and negative terminals of the battery. Make sure the wire is in contact with each battery terminal. Be careful, as sometimes the terminals can get warm!</span>', 
                textPosition: 'bottom',
                textRatio: 'oneThird', 
                withAudio: false,
            },
            {
                type: "gallery", 
                galleryId:'page3Gallery_7',  
                galleryCaption:'Step 5: Using',
                galleryThumb:'images/page3/RUS_L2_M6_mov_8_sml.jpg', 
                galleryVideo:'videos/page3/RUS_L2_M6_mov_8.mov', 
                galleryText:'<img src="images/audio-icon.png" class="audioIcon audio-icon" audiosource="sounds/page3/RUS_L2_M6_SB_003_A006.mp3" alt=""/><span class="audioText">Step 5: Place the tip of your electromagnet in your pile of paper clips and lift it up, picking up as many paper clips as it can lift.</span>', 
                textPosition: 'bottom',
                textRatio: 'oneThird', 
                withAudio: false,
            },
            {
                type: "gallery", 
                galleryId:'page3Gallery_8',  
                galleryCaption:'Step 6: Disconnecting',
                galleryThumb:'images/page3/RUS_L2_M6_mov_10_sml.jpg', 
                galleryVideo:'videos/page3/RUS_L2_M6_mov_10.mov', 
                galleryText:'<img src="images/audio-icon.png" class="audioIcon audio-icon" audiosource="sounds/page3/RUS_L2_M6_SB_003_A007.mp3" alt=""/><span class="audioText">Step 6: To save your battery, disconnect your circuit by removing at least one wire from either battery terminal.</span>', 
                textPosition: 'bottom',
                textRatio: 'oneThird', 
                withAudio: false,
            },
            {
                type: "gallery", 
                galleryId:'page3Gallery_9', 
                galleryCaption:'Step 7: Observations',
                galleryTitle:'Initial Observations', 
                galleryThumb:'images/page3/RUS_L2_M6_mov_1_sml.jpg', 
                galleryImage:'images/page3/RUS_L2_M6_mov_1.jpg', 
                galleryText:'<img src="images/audio-icon.png" class="audioIcon audio-icon" audiosource="sounds/page3/RUS_L2_M6_SB_003_A008.mp3" alt=""/><span class="audioText">Step 7: Write down some initial observations in your science journal. How do you turn the magnet on and off? How strong is the magnet? What else can you observe from this initial experiment? View the slideshow again to help you think of other observations.</span>', 
                textPosition: 'bottom',
                textRatio: 'oneThird', 
                withAudio: false,
            }
        ],
        isThumbnail         :   false,
        withRubric      :   false,
        fullScreenHeight    :   '93%',
        template        :   templateType.RiseBlue,
        componentPageName:  'page3'
    });
    